openapi: 3.0.0
info:
  title: LunaSoft Product API
  version: 1.0.10

  description: |
    LST Product API for client integrate our product on fund wallet

    > Lunasoft will send the test integration with `(endpoint_url)`, `(X-BLS-KEY)`, `(X-Vendor-ID)`, `(Sign)`
    to you. Your service agent must provider credential. which should be successfully integrated.

    ---

    ### Release Version:

    V1.0.0 - 2023/01/25
    - Add create member, increase / decrease credit, and balance.

    V1.0.1 - 2023/01/31
    - Add launch game and game status.

    V1.0.2 - 2023/02/15
    - Add win loss, statement, outstanding and outstanding detail report.

    V1.0.3 - 2023/02/27
    - Update response status code.

    V1.0.4 - 2023/03/01
    - Update game code.
    - Update request body in route `/report/outstanding` and `/report/outstanding_detail`.

    V1.0.5 - 2023/03/03
    - Add game list.
    
    V1.0.6 - 2023/03/16
    - Add game_code in request body in route `/report/...`.
    - Update request body in route `/report/outstanding` .
    
    V1.0.7 - 2023/03/16
    - Change game_code to provider_code in route `/report/...`
    - Update request body in route `/launch_game`
    
    V1.0.8 - 2023/03/31
    - Add game_list_fishing
    
    V1.0.9 - 2023/04/08
    - Add member login to lobby

    V1.0.9 - 2023/04/10
    - Add bet log
    - Remove outstanding detail
    - Update body of win loss report and outstanding
    
    ---

    ### Authorization:
    | Key | In | Description 
    |-----|-----|-----
    | X-BLS-Key | Header |  BillionSoft Key please ask our information
    | X-Vendor-ID | Header | Vendor ID generate by BillionSoft ask our information
    | Sign | Body | Sign is the signature key

    </br>

    ### Status Code:
    | Status Code | Description
    |-----|-----
    | 0 | Response Success
    | 14001 | Missing Body
    | 14002 | Invalid Body Type
    | 14003 | Invalid Body Pattern
    | 14004 | Credit Insufficient
    | 14006 | Member not found 
    | 14031 | Access Denied
    | 14012 | Unauthorized
    | 14091 | Data not found
    | 14092 | Data duplication
    | 15001 | Service Error <b>Please contact support.</b>

    </br>

    ### Game Code:
    | Provider Code | Provider Name
    |-----|-----
    | JK | JokerGaming
    | PG | PGSoft
    | PP | PragmaticPlay
    | AMBS | AMB Slot
    | AMBP | AMB Poker
    | RT | Red Tiger
    | CQ9 | CQ9
    | SPG | Spade Gaming
    | JL | Jili
    | DGS | DragoonSoft
    | NSP | Next Spin
    | SPP | Simple Play
    | I8 | i8Games
    | EDP | Endorphina
    | PPL | PlayPearls
    | JP | JustPlay
    | NET | NetEnt
    | SML | Slot Mill
    | SA | SA Gaming
    | SX | SexyBaccarat
    | WM | WM Casino
    | XT | XtreamGaming
    | AB | AllBet
    | DGC | DreamGaming
    | VVG | VivoGaming
    | BG | Big Gaming
    | EBT | EBET
    | PPC | PragmaticPlay Casino
    | UBT | UBETT
    | RG | Royal GClub
    | RSG | Royal Slot Game

  contact:
    name: API Support LunaSoft Team
    email: developer@lunasoft.co
    
servers:
  - url: https://{endpoint_url}
paths:
  /create_member:
   post:
      summary: Create Member
      description: |
        member is unique value. we recommended to add prefixes when register ex blsmb0001
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: 'member001'
                  minLength: 6
                  maxLength: 18
                password:
                  type: string
                  example: 'a@1234'
                  description: 'Password should be at 6 - 24 characters long and at least one special character.'
                  minLength: 6
                  maxLength: 24
                phone_number_contact:
                  type: string
                  example: '098765431'
                  minLength: 9
                memo:
                  type: string
                  example : 'memo'
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + password + x-vendor-id)`
                  example: '4d9bf50cdb08e6796a772ca36f0d0dff'
              required:
                - username
                - password
                - sign
      responses:
        '200':
          description: 'Response Success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 0
                  payload:
                    type: object
                    properties:
                      username:
                        type: string
                        example: 'member001'
                        minLength: 6
                        maxLength: 24
        '500':
          description: 'Error'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 15001,
                    servers:

  /change_password:
   post:
      summary:  Change Password
      description: Change member password by agent.
      requestBody:
        content:
          application/json:
                       schema:
              properties:
                username:
                  type: string
                  example: member001
                new_password:
                  type: string
                  example: 1234@b
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + new_password + x-vendor-id)`
                  example: '4d9bf50cdb08e6796a772ca36f0d0dff'
              required:
                - username
                - new_password
                - sign


 
  /store/inventory:
    get:
      tags:
        - store
      summary: Returns pet inventories by status
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
      security:
        - api_key: []
  /store/order:
    post:
      tags:
        - store
      summary: Place an order for a pet
      description: ''
      operationId: placeOrder
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid Order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order placed for purchasing the pet
        required: true
  '/store/order/{orderId}':
    get:
      tags:
        - store
      summary: Find purchase order by ID
      description: >-
        For valid response try integer IDs with value >= 1 and <= 10. Other
        values will generated exceptions
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of pet that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 10
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
    delete:
      tags:
        - store
      summary: Delete purchase order by ID
      description: >-
        For valid response try integer IDs with positive integer value. Negative
        or non-integer values will generate API errors
      operationId: deleteOrder
      parameters:
        - name: orderId
          in: path
          description: ID of the order that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true
  /user/createWithArray:
    post:
      tags:
        - user
      summary: Creates list of users with given input array
      description: ''
      operationId: createUsersWithArrayInput
      responses:
        default:
          description: successful operation
      requestBody:
        $ref: '#/components/requestBodies/UserArray'
  /user/createWithList:
    post:
      tags:
        - user
      summary: Creates list of users with given input array
      description: ''
      operationId: createUsersWithListInput
      responses:
        default:
          description: successful operation
      requestBody:
        $ref: '#/components/requestBodies/UserArray'
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        '400':
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      responses:
        default:
          description: successful operation
  '/user/{username}':
    get:
      tags:
        - user
      summary: Get user by user name
      description: ''
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be updated
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Updated user object
        required: true
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  responses:
    PetResponse:
      description: successful operation
      content:
        application/xml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Pet'
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Pet'
  requestBodies:
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true
    Pet:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
      description: Pet object that needs to be added to the store
      required: true
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          format: int32
          description: User Status
      xml:
        name: User
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Category
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    Pet:
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: Pet
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
