openapi: 3.0.3
servers:
  - url: '//petstore.swagger.io/v2'
info:
  description: >-
    This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).  For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
paths:
  /create_member:
    post:
      summary: Create Member
      description: |
        member is unique value. we recommended to add prefixes when register ex blsmb0001
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: 'member001'
                  minLength: 6
                  maxLength: 18
                password:
                  type: string
                  example: 'a@1234'
                  description: 'Password should be at 6 - 24 characters long and at least one special character.'
                  minLength: 6
                  maxLength: 24
                phone_number_contact:
                  type: string
                  example: '098765431'
                  minLength: 9
                memo:
                  type: string
                  example : 'memo'
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + password + x-vendor-id)`
                  example: '4d9bf50cdb08e6796a772ca36f0d0dff'
              required:
                - username
                - password
                - sign
      responses:
        '200':
          description: successful
        '500':
          description: Error

 
  /change_password:
    post:
      summary:  Change Password
      description: Change member password by agent.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  example: member001
                new_password:
                  type: string
                  example: 1234@b
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + new_password + x-vendor-id)`
                  example: '4d9bf50cdb08e6796a772ca36f0d0dff'
              required:
                - username
                - password
                - sign
      responses:
        '200':
          description: successful 
        '500':
          description: Error
  /balance:
    post:
      summary: 'Member Balance'
      description: 'Call Member Balance'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: 'member001'
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + x-vendor-id)`
                  example: 'a3b2f435648d8a38eabb7d968332701b'
      responses:
        '200':
          description: successful 
        '500':
          description: Error       
          
  /increase_credit:
    post:
      summary: 'Increase Credit'
      description: increase your member credit.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  example: 'member001'
                amount:
                  type: number
                  example: 50.0
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + amount + x-vendor-id)`
                  example: '4d9bf50cdb08e6796a772ca36f0d0dff'
      responses:
        '200':
          description: successful
        '500':
          description: Error

  /decrease_credit:
    post:
      summary: 'Decrease Credit'
      description: decrease your member credit.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  example: 'member001'
                amount:
                  type: number
                  example: 50.0
                sign:
                  type: string
                  description: |
                    `HMACMD5(username + amount + x-vendor-id)`
                  example: '4d9bf50cdb08e6796a772ca36f0d0dff'
      responses:
        '200':
          description: successful
        '500':
          description: Error
          
  /game_list:
    get:
      summary: 'Game List (Slot Game Only)'
      description: |
        Get the game URL with provider_code, the game is redirected to the lobby via this link. See **Provider Code** Section.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                provider_code:
                  type: string
                  example: "JK"
                sign:
                  type: string
                  description: |
                    `HMACMD5(provider_code + x-vendor-id)`
                  example: 'a3b2f435648d8a38eabb7d968332701b'
      responses:
        '200':
          description: successful
        '500':
          description: Error
          
   /game_fishing:
    get:
      summary: 'Game List (Fish Game Only)'
 
 
